#-------------------------------------------------------------------------------
# Database settings
#-------------------------------------------------------------------------------
DB_NAME:
DB_USERNAME:
DB_PASSWORD:
